<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VehicleInventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample bus records
        $vehicleInventory = [
            [
                'vehicle_number' => 'BUS-001',
                'driver_name' => 'Juan Dela Cruz',
                'route_from' => 'Manila',
                'route_to' => 'Laoag',
                'total_capacity' => 50, // Seats
                'available_capacity' => 40,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-001.jpg', // Example image path
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-002',
                'driver_name' => 'Maria Santos',
                'route_from' => 'Laoag',
                'route_to' => 'Manila',
                'total_capacity' => 45,
                'available_capacity' => 20,
                'status' => 'maintenance',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-002.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-003',
                'driver_name' => 'Pedro Reyes',
                'route_from' => 'Manila',
                'route_to' => 'Laoag',
                'total_capacity' => 60,
                'available_capacity' => 55,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-003.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-004',
                'driver_name' => 'Ana Garcia',
                'route_from' => 'Manila',
                'route_to' => 'Laoag',
                'total_capacity' => 50,
                'available_capacity' => 45,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-004.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-005',
                'driver_name' => 'Luis Mendoza',
                'route_from' => 'Laoag',
                'route_to' => 'Manila',
                'total_capacity' => 48,
                'available_capacity' => 30,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-005.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-006',
                'driver_name' => 'Clara Ramirez',
                'route_from' => 'Manila',
                'route_to' => 'Laoag',
                'total_capacity' => 55,
                'available_capacity' => 20,
                'status' => 'maintenance',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-006.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-007',
                'driver_name' => 'Carlos Cruz',
                'route_from' => 'Laoag',
                'route_to' => 'Manila',
                'total_capacity' => 60,
                'available_capacity' => 50,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-007.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-008',
                'driver_name' => 'Josefina Lopez',
                'route_from' => 'Manila',
                'route_to' => 'Laoag',
                'total_capacity' => 40,
                'available_capacity' => 35,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-008.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-009',
                'driver_name' => 'Erwin Castro',
                'route_from' => 'Laoag',
                'route_to' => 'Manila',
                'total_capacity' => 45,
                'available_capacity' => 40,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-009.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-010',
                'driver_name' => 'Fatima Perez',
                'route_from' => 'Manila',
                'route_to' => 'Laoag',
                'total_capacity' => 55,
                'available_capacity' => 50,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-010.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-011',
                'driver_name' => 'Marco Villanueva',
                'route_from' => 'Laoag',
                'route_to' => 'Manila',
                'total_capacity' => 50,
                'available_capacity' => 45,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-011.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-012',
                'driver_name' => 'Juanita Morales',
                'route_from' => 'Baguio',
                'route_to' => 'Laoag',
                'total_capacity' => 50,
                'available_capacity' => 30,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-012.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-013',
                'driver_name' => 'David Cruz',
                'route_from' => 'Laoag',
                'route_to' => 'Baguio',
                'total_capacity' => 60,
                'available_capacity' => 50,
                'status' => 'maintenance',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-013.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-014',
                'driver_name' => 'Jonathan Perez',
                'route_from' => 'Baguio',
                'route_to' => 'Laoag',
                'total_capacity' => 55,
                'available_capacity' => 50,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-014.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-015',
                'driver_name' => 'Rafael Garcia',
                'route_from' => 'Laoag',
                'route_to' => 'Baguio',
                'total_capacity' => 50,
                'available_capacity' => 30,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-015.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-016',
                'driver_name' => 'Eleanor Cruz',
                'route_from' => 'Baguio',
                'route_to' => 'Laoag',
                'total_capacity' => 48,
                'available_capacity' => 25,
                'status' => 'maintenance',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-016.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-017',
                'driver_name' => 'Victor Santos',
                'route_from' => 'Laoag',
                'route_to' => 'Baguio',
                'total_capacity' => 60,
                'available_capacity' => 40,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-017.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-018',
                'driver_name' => 'Maria Villanueva',
                'route_from' => 'Baguio',
                'route_to' => 'Laoag',
                'total_capacity' => 55,
                'available_capacity' => 50,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-018.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-019',
                'driver_name' => 'Carlos Garcia',
                'route_from' => 'Laoag',
                'route_to' => 'Baguio',
                'total_capacity' => 50,
                'available_capacity' => 20,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-019.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-020',
                'driver_name' => 'Cynthia Ramos',
                'route_from' => 'Baguio',
                'route_to' => 'Laoag',
                'total_capacity' => 60,
                'available_capacity' => 55,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-020.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-021',
                'driver_name' => 'Lorenzo Cruz',
                'route_from' => 'Laoag',
                'route_to' => 'Baguio',
                'total_capacity' => 45,
                'available_capacity' => 25,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-021.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_number' => 'BUS-022',
                'driver_name' => 'Angelina Reyes',
                'route_from' => 'Baguio',
                'route_to' => 'Laoag',
                'total_capacity' => 50,
                'available_capacity' => 30,
                'status' => 'ready',
                'last_updated' => Carbon::now(),
                'image' => 'vehicles/bus-022.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];        

        DB::table('vehicle_inventories')->insert($vehicleInventory);
    }
}
